# Redirection de / vers l'accueil du blog
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: articles_all
        permanent: true
        keepQueryParams: true
        keepRequestMethod: true
